from bmmo.parsing import get_bmap_measures


def test_map_with_few_objects():
    bmap = {"OBJ0": {"Y": "330", "LogicID": "3", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "587", "ID": "0",
                     "Name": "USC CTF Flag", "Team": "1", "ObjIndexID": "10"},
            "OBJ4": {"Y": "328", "LogicID": "1", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "584", "ID": "4",
                     "Name": "USC Spawn", "Team": "1", "ObjIndexID": "8"},
            "OBJ2": {"Y": "384", "LogicID": "5", "Poly": "0", "ObjRotate": "0", "ObjIsTile": "1", "Depth": "0",
                     "X": "512", "ObjAnimSpeed": "1", "ID": "2", "Name": "Alien block.png", "Team": "-1",
                     "ObjIndexID": "1"},
            "OBJ5": {"Y": "570", "LogicID": "2", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "600", "ID": "5",
                     "Name": "THE MAN Spawn", "Team": "2", "ObjIndexID": "9"},
            "OBJ1": {"Y": "331", "LogicID": "4", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "588", "ID": "1",
                     "Name": "THE MAN CTF Flag", "Team": "2", "ObjIndexID": "11"},
            "Config": {"Author": "Shaigro", "TotalGates": "6", "Bkgd1MD5": "", "SeaLevel": "0", "Ambience": "0",
                       "Bkgd2Hspeed": "0", "MapWidth": "768", "ShowLog": "0", "Bkgd2HPara": "0", "Bkgd1File": "",
                       "BkgdColor2": "15043165", "ShowPath": "0", "Bkgd1AmbCol": "4210752", "Preview": "",
                       "Bkgd1VPara": "0", "Bkgd3Vspeed": "0", "Bkgd3VPara": "0", "Workshop": "-1", "Bkgd1Vspeed": "0",
                       "Bkgd3File": "", "SeaDepth": "-200", "Grap": "1", "Bkgd3MD5": "", "DivChc": "25",
                       "BkgdColor1": "2217333", "MapHeight": "896", "Bkgd1Hspeed": "0", "ShowCol": "0",
                       "Bkgd3Hspeed": "0", "SeaType": "0", "Bkgd1HPara": "0", "Bkgd3HPara": "0", "Name": "Speedrun CTF",
                       "Bkgd2File": "", "Bkgd1Amb": "8", "DecalDepth": "-200", "Bkgd2Vspeed": "0", "Bkgd2MD5": "",
                       "Climb": "0", "Bkgd2VPara": "0"},
            "OBJ3": {"Y": "384", "LogicID": "0", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                     "X": "512", "ObjSound": "0", "ID": "3", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"}
            }
    expected_width = 768
    expected_height = 896

    width, height = get_bmap_measures(bmap)

    assert (width, height) == (expected_width, expected_height)


def test_map_with_lots_of_objects():
    bmap = {
        "OBJ60": {"Y": "384", "LogicID": "0", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "512",
                  "ObjSound": "0", "ID": "60", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ0": {"Y": "0", "LogicID": "62", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "640",
                 "ObjSound": "0", "ID": "0", "Name": "Block (1x4)", "Team": "-1", "ObjIndexID": "43"},
        "OBJ20": {"Y": "512", "LogicID": "24", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "20", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ45": {"Y": "384", "LogicID": "23", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "45", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ41": {"Y": "384", "LogicID": "30", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "384", "ObjSound": "0", "ID": "41", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ4": {"Y": "0", "LogicID": "58", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "128",
                 "ObjSound": "0", "ID": "4", "Name": "Block (1x4)", "Team": "-1", "ObjIndexID": "43"},
        "OBJ24": {"Y": "640", "LogicID": "32", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "384", "ObjSound": "0", "ID": "24", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ47": {"Y": "128", "LogicID": "21", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "47", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ49": {"Y": "384", "LogicID": "16", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "128", "ObjSound": "0", "ID": "49", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ2": {"Y": "0", "LogicID": "60", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "384",
                 "ObjSound": "0", "ID": "2", "Name": "Block (1x4)", "Team": "-1", "ObjIndexID": "43"},
        "OBJ22": {"Y": "768", "LogicID": "26", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "22", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ62": {"Y": "570", "LogicID": "2", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "600", "ID": "62",
                  "Name": "THE MAN Spawn", "Team": "2", "ObjIndexID": "9"},
        "OBJ6": {"Y": "512", "LogicID": "56", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "512",
                 "ObjSound": "0", "ID": "6", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ26": {"Y": "512", "LogicID": "38", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "512", "ObjSound": "0", "ID": "26", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ28": {"Y": "768", "LogicID": "40", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "512", "ObjSound": "0", "ID": "28", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ8": {"Y": "0", "LogicID": "54", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "512",
                 "ObjSound": "0", "ID": "8", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ43": {"Y": "128", "LogicID": "28", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "384", "ObjSound": "0", "ID": "43", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ30": {"Y": "768", "LogicID": "47", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "640", "ObjSound": "0", "ID": "30", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ15": {"Y": "512", "LogicID": "10", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "15", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ55": {"Y": "128", "LogicID": "7", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "55", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ11": {"Y": "0", "LogicID": "51", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "256",
                  "ObjSound": "0", "ID": "11", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ51": {"Y": "128", "LogicID": "14", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "128", "ObjSound": "0", "ID": "51", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ34": {"Y": "256", "LogicID": "43", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "640", "ObjSound": "0", "ID": "34", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ19": {"Y": "768", "LogicID": "19", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "128", "ObjSound": "0", "ID": "19", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ57": {"Y": "330", "LogicID": "3", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "587", "ID": "57",
                  "Name": "USC CTF Flag", "Team": "1", "ObjIndexID": "10"},
        "OBJ59": {"Y": "384", "LogicID": "5", "Poly": "0", "ObjRotate": "0", "ObjIsTile": "1", "Depth": "0", "X": "512",
                  "ObjAnimSpeed": "1", "ID": "59", "Name": "Alien block.png", "Team": "-1", "ObjIndexID": "1"},
        "OBJ17": {"Y": "512", "LogicID": "17", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "128", "ObjSound": "0", "ID": "17", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ32": {"Y": "512", "LogicID": "45", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "640", "ObjSound": "0", "ID": "32", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ36": {"Y": "0", "LogicID": "41", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "640",
                  "ObjSound": "0", "ID": "36", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ38": {"Y": "256", "LogicID": "36", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "512", "ObjSound": "0", "ID": "38", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ53": {"Y": "384", "LogicID": "9", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "53", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ13": {"Y": "256", "LogicID": "49", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "13", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ40": {"Y": "0", "LogicID": "34", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "512",
                  "ObjSound": "0", "ID": "40", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ25": {"Y": "768", "LogicID": "33", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "384", "ObjSound": "0", "ID": "25", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ5": {"Y": "0", "LogicID": "57", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                 "ObjSound": "0", "ID": "5", "Name": "Block (1x4)", "Team": "-1", "ObjIndexID": "43"},
        "OBJ21": {"Y": "640", "LogicID": "25", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "21", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ1": {"Y": "0", "LogicID": "61", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "512",
                 "ObjSound": "0", "ID": "1", "Name": "Block (1x4)", "Team": "-1", "ObjIndexID": "43"},
        "OBJ61": {"Y": "328", "LogicID": "1", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "584", "ID": "61",
                  "Name": "USC Spawn", "Team": "1", "ObjIndexID": "8"},
        "OBJ44": {"Y": "0", "LogicID": "27", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "384",
                  "ObjSound": "0", "ID": "44", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ9": {"Y": "512", "LogicID": "53", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "256",
                 "ObjSound": "0", "ID": "9", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ29": {"Y": "640", "LogicID": "11", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "29", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ27": {"Y": "640", "LogicID": "39", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "512", "ObjSound": "0", "ID": "27", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ7": {"Y": "256", "LogicID": "55", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "512",
                 "ObjSound": "0", "ID": "7", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ42": {"Y": "256", "LogicID": "29", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "384", "ObjSound": "0", "ID": "42", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ48": {"Y": "0", "LogicID": "20", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "256",
                  "ObjSound": "0", "ID": "48", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ46": {"Y": "256", "LogicID": "22", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "46", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "Config": {"Author": "Shaigro", "TotalGates": "63", "Bkgd1MD5": "", "SeaLevel": "0", "Ambience": "0",
                   "Bkgd2Hspeed": "0", "MapWidth": "768", "ShowLog": "0", "Bkgd2HPara": "0", "Bkgd1File": "",
                   "BkgdColor2": "15043165", "ShowPath": "0", "Bkgd1AmbCol": "4210752", "Preview": "",
                   "Bkgd1VPara": "0", "Bkgd3Vspeed": "0", "Bkgd3VPara": "0", "Workshop": "-1", "Bkgd1Vspeed": "0",
                   "Bkgd3File": "", "SeaDepth": "-200", "Grap": "1", "Bkgd3MD5": "", "DivChc": "25",
                   "BkgdColor1": "2217333", "MapHeight": "896", "Bkgd1Hspeed": "0", "ShowCol": "0", "Bkgd3Hspeed": "0",
                   "SeaType": "0", "Bkgd1HPara": "0", "Bkgd3HPara": "0", "Name": "Speedrun CTF", "Bkgd2File": "",
                   "Bkgd1Amb": "8", "DecalDepth": "-200", "Bkgd2Vspeed": "0", "Bkgd2MD5": "", "Climb": "0",
                   "Bkgd2VPara": "0"},
        "OBJ23": {"Y": "512", "LogicID": "31", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "384", "ObjSound": "0", "ID": "23", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ3": {"Y": "0", "LogicID": "59", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "256",
                 "ObjSound": "0", "ID": "3", "Name": "Block (1x4)", "Team": "-1", "ObjIndexID": "43"},
        "OBJ50": {"Y": "256", "LogicID": "15", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "128", "ObjSound": "0", "ID": "50", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ10": {"Y": "256", "LogicID": "52", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "256", "ObjSound": "0", "ID": "10", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ35": {"Y": "128", "LogicID": "42", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "640", "ObjSound": "0", "ID": "35", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ31": {"Y": "640", "LogicID": "46", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "640", "ObjSound": "0", "ID": "31", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ54": {"Y": "256", "LogicID": "8", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "54", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ14": {"Y": "0", "LogicID": "48", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "14", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ39": {"Y": "128", "LogicID": "35", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "512", "ObjSound": "0", "ID": "39", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ37": {"Y": "384", "LogicID": "37", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "512", "ObjSound": "0", "ID": "37", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ12": {"Y": "512", "LogicID": "50", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "12", "Name": "Block (2x2)", "Team": "-1", "ObjIndexID": "63"},
        "OBJ52": {"Y": "0", "LogicID": "13", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "128",
                  "ObjSound": "0", "ID": "52", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ16": {"Y": "768", "LogicID": "12", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "16", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ58": {"Y": "331", "LogicID": "4", "Poly": "0", "ObjIsTile": "0", "Depth": "-250", "X": "588", "ID": "58",
                  "Name": "THE MAN CTF Flag", "Team": "2", "ObjIndexID": "11"},
        "OBJ56": {"Y": "0", "LogicID": "6", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0", "X": "0",
                  "ObjSound": "0", "ID": "56", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ18": {"Y": "640", "LogicID": "18", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "128", "ObjSound": "0", "ID": "18", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"},
        "OBJ33": {"Y": "384", "LogicID": "44", "Poly": "0", "ObjIsTile": "0", "Depth": "500", "ObjType": "0",
                  "X": "640", "ObjSound": "0", "ID": "33", "Name": "Block (1x1)", "Team": "-1", "ObjIndexID": "0"}
    }

    expected_width = 768
    expected_height = 896

    width, height = get_bmap_measures(bmap)

    assert (width, height) == (expected_width, expected_height)